name: Backend OnRender Deployment

# on:
#   push:
#     branches: [ main ] 
# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3

#       - name: Use Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: 18

#       - name: Install dependencies
#         working-directory: ./server
#         run: npm ci

#       - name: Deploy to Render
#         env:
#           RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
#         run: curl -X POST $RENDER_DEPLOY_HOOK_URL

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./server
        run: npm ci

      - name: Build backend
        working-directory: ./server
        run: npm run build

      - name: Run tests
        working-directory: ./server
        run: npm test

  deploy_backend:
    runs-on: ubuntu-latest
    needs: build_and_test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./server
        run: npm ci

      - name: Build backend
        working-directory: ./server
        run: npm run build

      - name: Deploy to Render
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: curl -X POST $RENDER_DEPLOY_HOOK
